CREATE TABLE BOOK ( 
BOOK_ID INT (10) PRIMARY KEY, 
TITLE VARCHAR (20), 
PUB_YEAR VARCHAR (20), 
PUBLISHER_NAME VARCHAR (20), 
FOREIGN KEY (PUBLISHER_NAME) REFERENCES PUBLISHER (NAME) ON DELETE 
CASCADE); 

CREATE TABLE BOOK_AUTHORS ( 
AUTHOR_NAME VARCHAR (20), 
BOOK_ID INT (10), 
PRIMARY KEY (BOOK_ID, AUTHOR_NAME), 
FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE); 
CREATE TABLE PUBLISHER ( 
NAME VARCHAR (20) PRIMARY KEY, 
PHONE BIGINT (20), 
ADDRESS VARCHAR (100)); 

CREATE TABLE BOOK_COPIES ( 
NO_OF_COPIES INT (5), 
BOOK_ID INT (10), 
PROGRAMME_ID INT (10), 
PRIMARY KEY (BOOK_ID,PROGRAMME_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE, 
FOREIGN KEY (PROGRAMME_ID) REFERENCES LIBRARY_PROGRAMME 
(PROGRAMME_ID) ON DELETE CASCADE);

CREATE TABLE BOOK_LENDING ( 
DATE_OUT DATE, 
DUE_DATE DATE, 
BOOK_ID INT (10), 
PROGRAMME_ID INT (10), 
CARD_NO INT (10), 
PRIMARY KEY (BOOK_ID,PROGRAMME_ID, CARD_NO), 
FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE, 
FOREIGN KEY (PROGRAMME_ID) REFERENCES 
LIBRARY_PROGRAMME(PROGRAMME_ID) ON DELETE CASCADE, 
FOREIGN KEY (CARD_NO) REFERENCES CARD (CARD_NO) ON DELETE CASCADE); 

CREATE TABLE CARD ( 
CARD_NO INT (10) PRIMARY KEY);

CREATE TABLE LIBRARY_PROGRAMME ( 
PROGRAMME_ID INT (10) PRIMARY KEY, 
PROGRAMME_NAME VARCHAR (50), 
ADDRESS VARCHAR (100)); 
